### ISSUE TITLE
out of memory with GTX980

### ISSUE THREAD

**Issue by Hunterwolf88** [adeshpande3/Facebook-Messenger-Bot#24]
Hello there!
I completed succesfully the awesome tutorial except the training (Seq2Seq.py) itself: everytime I do that I run out of memory. What can I do to fix that?
I tried to reduce the "batchSize = 24" with no results.
I'm trying 256 dimensions word vectors.
Sorry for the noob question, I'm new in the world of deep learning, especially with GPU processing.

Ubuntu 16.04
GPU: NVIDIA Geforce GTX 980
RAM: 16 GB
Tensorflow-GPU 1.6.0, Python 2.7, Cuda 9.0, cuDNN 7

this is what i get:

`Traceback (most recent call last):
  File "Seq2Seq.py", line 228, in <module>
    curLoss, _, pred = sess.run([loss, optimizer, decoderPrediction], feed_dict=feedDict)
  File "/home/hunterwolf/anaconda3/envs/tensorflow27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/hunterwolf/anaconda3/envs/tensorflow27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/hunterwolf/anaconda3/envs/tensorflow27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/home/hunterwolf/anaconda3/envs/tensorflow27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[295899,112] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: Adam/update_embedding_rnn_seq2seq/embedding_rnn_decoder/embedding/mul_5 = Mul[T=DT_FLOAT, _class=["loc:@embedding_rnn_seq2seq/embedding_rnn_decoder/embedding"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](embedding_rnn_seq2seq/embedding_rnn_decoder/embedding/Adam_1/read, Adam/beta2)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Node: beta2_power/read/_113 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_262_beta2_power/read", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Caused by op u'Adam/update_embedding_rnn_seq2seq/embedding_rnn_decoder/embedding/mul_5', defined at:
  File "Seq2Seq.py", line 196, in <module>
    optimizer = tf.train.AdamOptimizer(1e-4).minimize(loss)
  File "/home/hunterwolf/anaconda3/envs/tensorflow27/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 369, in minimize
    name=name)
  File "/home/hunterwolf/anaconda3/envs/tensorflow27/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 532, in apply_gradients
    update_ops.append(processor.update_op(self, grad))
  File "/home/hunterwolf/anaconda3/envs/tensorflow27/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 118, in update_op
    return optimizer._apply_sparse_duplicate_indices(g, self._v)
  File "/home/hunterwolf/anaconda3/envs/tensorflow27/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 798, in _apply_sparse_duplicate_indices
    return self._apply_sparse(gradient_no_duplicate_indices, var)
  File "/home/hunterwolf/anaconda3/envs/tensorflow27/lib/python2.7/site-packages/tensorflow/python/training/adam.py", line 199, in _apply_sparse
    lambda x, i, v: state_ops.scatter_add(  # pylint: disable=g-long-lambda
  File "/home/hunterwolf/anaconda3/envs/tensorflow27/lib/python2.7/site-packages/tensorflow/python/training/adam.py", line 187, in _apply_sparse_shared
    v_t = state_ops.assign(v, v * beta2_t, use_locking=self._use_locking)
  File "/home/hunterwolf/anaconda3/envs/tensorflow27/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 780, in _run_op
    return getattr(ops.Tensor, operator)(a._AsTensor(), *args)
  File "/home/hunterwolf/anaconda3/envs/tensorflow27/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 934, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/hunterwolf/anaconda3/envs/tensorflow27/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 1161, in _mul_dispatch
    return gen_math_ops._mul(x, y, name=name)
  File "/home/hunterwolf/anaconda3/envs/tensorflow27/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2789, in _mul
    "Mul", x=x, y=y, name=name)
  File "/home/hunterwolf/anaconda3/envs/tensorflow27/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/hunterwolf/anaconda3/envs/tensorflow27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/home/hunterwolf/anaconda3/envs/tensorflow27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[295899,112] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: Adam/update_embedding_rnn_seq2seq/embedding_rnn_decoder/embedding/mul_5 = Mul[T=DT_FLOAT, _class=["loc:@embedding_rnn_seq2seq/embedding_rnn_decoder/embedding"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](embedding_rnn_seq2seq/embedding_rnn_decoder/embedding/Adam_1/read, Adam/beta2)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Node: beta2_power/read/_113 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_262_beta2_power/read", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.`

**Comment by adeshpande3** [comment]
Is it giving you this error immediately when you start the training loop, or is it maybe after a particular number of iterations?

**Comment by Hunterwolf88** [comment]
The first time, after I run
`$ python Seq2Seq.py`
I got

```
/home/hunterwolf/anaconda3/envs/tensorflow27/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Since we cant find an embedding matrix, how many dimensions do you want your word vectors to be?:
```
After prompting the number (I tried 256, 512, 1000 with no real difference) I got this error after 30-40 minutes. The files Seq2SeqXTrain.py and Seq2SeqYTrain.npy are created but nothing else.

If I try again the error occurs after 5-10 seconds, if I delete them and try again the error occurs after about half an hour again. During this time I have no output, the terminal looks frozen, but I can use the computer normally.

**Comment by adeshpande3** [comment]
If the error occurs after 5-10 seconds when you run again, I'm assuming that most of the 30-40 minutes will be spent in the createTrainingMatrices function. Which means that the out of memory error is probably happening at the very beginning of the training loop (correct me if I'm wrong). Therefore it seems like there is something wrong with the amount of memory the initial model is taking up. Maybe you could post information about the size of Seq2SeqXTrain, Seq2SeqYTrain, batchSize, numLSTMUnits, etc and then we can try to see if there's some value that is off.

**Comment by Hunterwolf88** [comment]
Hello, thank you so much, I'm still trying to understand what is happening!

I tried different batch sizes (even 10, 5 ,2) but nothing changes.

I noticed from the nvidia-smi that the GPU memory (4 GB total) is almost full, but everything else is 0%, like:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.48                 Driver Version: 390.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980     Off  | 00000000:01:00.0  On |                  N/A |
|  0%   45C    P0    48W / 196W |   3670MiB /  4040MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

```
I can also see a computational process appears in the list below while training.

Seq2SeqXTrain.npy and Seq2SeqYTrain.npy are both 4.1 MB.


thanks for your help

**Comment by adeshpande3** [comment]
What I think is happening is that there is something in the model initialization that is too large. Basically something in the below code.

![image](https://user-images.githubusercontent.com/13543909/38254164-64c37bf6-370d-11e8-9984-16fce11bf699.png)

 I don't believe anything in the training procedure (like batch size) is wrong because the program fails almost immediately after starting the training loop. If it's running out of memory at the very beginning, that means that something in the initial model is going wrong. 

I'd recommend starting with a very simple neural network architecture (without the call to tf.contrib.legacy_seq2seq.embedding_rnn_seq2seq), see if there are any problems in training, and then slowly work your way back to the original code.

**Comment by Hunterwolf88** [comment]
The problem was (for the GTX 980) an actual OOM, although I initially thought it was a computational issue due to some misconfiguration in my Python environment or in the Training script, seeing the GPU unused during all the process.
This allowed me to identify the problem for my low-memory GPU, as you stated, in the network architecture itself and I was able to solve my problem with similar situations (so I think it can work in this case too), but I'm still too noob to find and suggest a valuable working fix (sorry).
If it can help you I'll try to investigate further, for example, at this point, I'd like to know if the Seq2SeqXTrain and Seq2SeqYTrain size has to do with the OOM in this scenario.

**Comment by adeshpande3** [comment]
Yeah, my initial thinking is that the size for those two matrices probably doesn't affect it, but it's more dependent on the size and computations in your initial network. Anyway, thanks, and glad your problem got solved :)
