### ISSUE TITLE
ValueError 

### ISSUE THREAD

**Issue by ozunaltun** [adeshpande3/Facebook-Messenger-Bot#35]
Hi all,
when i try to run seq2seq.py;

Finished loading training matrices
Traceback (most recent call last):
  File "seq.py", line 223, in <module>
    encoderTrain, decoderTargetTrain, decoderInputTrain = getTrainingBatch(xTrain, yTrain, batchSize, maxEncoderLength)
  File "seq.py", line 53, in getTrainingBatch
    num = randint(0,numTrainingExamples - localBatchSize - 1)
  File "C:\Users\ozun\Anaconda3\envs\tf-gpu\lib\random.py", line 221, in randint
    return self.randrange(a, b+1)
  File "C:\Users\ozun\Anaconda3\envs\tf-gpu\lib\random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,-12, -12)

**Comment by adeshpande3** [comment]
You should double check what your values are for numTrainingExamples and localBatchSize, and make sure they are positive and that the values make sense.

**Comment by ozunaltun** [comment]
How do i check those values? im using stock settings. thanks
