### ISSUE TITLE
Flask server deployment with Tensorflow error

### ISSUE THREAD

**Issue by lovincyrus** [adeshpande3/Facebook-Messenger-Bot#6]
While I'm at Step 8, I'm trying to deploy my Flask server to Heroku. I'm currently facing a Tensorflow error.

```
python -c 'import tensorflow as tf; print(tf.__version__)'
1.3.0
```

Here is the error:

```
ʕ•ﻌ•ʔ:cg2-flask cyrusgoh$ gunicorn app:app
[2017-09-16 00:03:10 -0700] [9531] [INFO] Starting gunicorn 19.7.1
[2017-09-16 00:03:10 -0700] [9531] [INFO] Listening at: http://127.0.0.1:8000 (9531)
[2017-09-16 00:03:10 -0700] [9531] [INFO] Using worker: sync
[2017-09-16 00:03:10 -0700] [9534] [INFO] Booting worker with pid: 9534
[2017-09-16 00:03:25 -0700] [9534] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/Users/gohloongkoon/Documents/git/cg2-flask/app.py", line 45, in <module>
    saver.restore(sess, tf.train.latest_checkpoint('models/'))
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [192] rhs shape= [448]
         [[Node: save/Assign_1 = Assign[T=DT_FLOAT, _class=["loc:@embedding_rnn_seq2seq/embedding_rnn_decoder/rnn_decoder/output_projection_wrapper/basic_lstm_cell/bias"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_rnn_seq2seq/embedding_rnn_decoder/rnn_decoder/output_projection_wrapper/basic_lstm_cell/bias, save/RestoreV2_1)]]

Caused by op u'save/Assign_1', defined at:
  File "/usr/local/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 203, in run
    super(Application, self).run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 202, in run
    self.manage_workers()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 544, in manage_workers
    self.spawn_workers()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 611, in spawn_workers
    self.spawn_worker()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/Users/gohloongkoon/Documents/git/cg2-flask/app.py", line 44, in <module>
    saver = tf.train.Saver()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1140, in __init__
    self.build()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1172, in build
    filename=self._filename)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 688, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 419, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/state_ops.py", line 274, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 43, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [192] rhs shape= [448]

         [[Node: save/Assign_1 = Assign[T=DT_FLOAT, _class=["loc:@embedding_rnn_seq2seq/embedding_rnn_decoder/rnn_decoder/output_projection_wrapper/basic_lstm_cell/bias"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_rnn_seq2seq/embedding_rnn_decoder/rnn_decoder/output_projection_wrapper/basic_lstm_cell/bias, save/RestoreV2_1)]]

[2017-09-16 00:03:25 -0700] [9534] [INFO] Worker exiting (pid: 9534)
[2017-09-16 00:03:26 -0700] [9531] [INFO] Shutting down: Master
[2017-09-16 00:03:26 -0700] [9531] [INFO] Reason: Worker failed to boot.
```

I can't seem to find the solution. This is the closest and the most similar question I could get — [Stackoverflow](https://stackoverflow.com/questions/40601975/tensorflow-assign-requires-shapes-of-both-tensors-to-match-lhs-shape-20-rhs)

In short, problem is `InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [192] rhs shape= [448]`

How do I reshape _rhs shape_ to 192, so lhs and rhs can have the size?

PS: Solutions I tried in line 42 app.py:
```
# Load in pretrained model
saver = tf.train.Saver()
# saver = tf.train.Saver(reshape=True)
# saver = tf.train.Saver(tf.global_variables, reshape=True)
```

**Comment by adeshpande3** [comment]
Normally, errors along those lines arise when the saved model is different from the pre-trained model. Double check to make sure that the shapes of all your variables are the same as the graph you saved, same number of LSTM units, etc. From your error, I think it has something to do with the number of LSTM units. Try increasing/decreasing that number to figure out if "lhs shape=[192] rhs shape=[448]" changes.

**Comment by lovincyrus** [comment]
Problem solved by changing: 

`lstmUnits = 112 # lhs shape= [448] rhs shape= [448]`

**Comment by Arvind6353** [comment]
@lovincyrus . I currently have lstmunits as 112 but getting the same error as above. Any help ?

**Comment by adeshpande3** [comment]
That means you need to change it to the number of units you had when you saved the model. From the other issue you opened up, it seems like you need 48 lstm units. Just change that number and then see if the argument error shows different lhs and rhs.
