### ISSUE TITLE
fbchat_archive_parser.parser.FacebookDataError

### ISSUE THREAD

**Issue by ckshitij** [adeshpande3/Facebook-Messenger-Bot#7]
[parse_file.zip](https://github.com/adeshpande3/Facebook-Messenger-Bot/files/1380462/parse_file.zip)

**Getting error at a time of parsing the message.htm file**
### fbcap ./messages.htm > fbMessages.txt
Traceback (most recent call last):
  ```
File "/Users/coddict/anaconda/bin/fbcap", line 11, in <module>
    load_entry_point('fbchat-archive-parser==1.0.post1', 'console_scripts', 'fbcap')()
  File "/Users/coddict/anaconda/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/coddict/anaconda/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/coddict/anaconda/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/coddict/anaconda/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/coddict/anaconda/lib/python3.6/site-packages/fbchat_archive_parser/main.py", line 118, in fbcap
    fbch = parser.parse()
  File "/Users/coddict/anaconda/lib/python3.6/site-packages/fbchat_archive_parser/parser.py", line 92, in parse
    self._parse_content()
  File "/Users/coddict/anaconda/lib/python3.6/site-packages/fbchat_archive_parser/parser.py", line 117, in _parse_content
    self._process_element(pos, element)
  File "/Users/coddict/anaconda/lib/python3.6/site-packages/fbchat_archive_parser/parser.py", line 250, in _process_element

```

**"An unrecoverable parsing error has occurred (missing timestamp data)"**
**fbchat_archive_parser.parser.FacebookDataError: An unrecoverable parsing error has occurred (missing timestamp data)**

**Comment by adeshpande3** [comment]
Seems like that's an issue with the fb parser. Check out Dillon's repo and maybe you can open an issue over there? https://github.com/ownaginatious/fbchat-archive-parser

**Comment by ckshitij** [comment]
Ok, Thank you so much. 👍
